from typing import Dict

from Options import DeathLink, OptionDict, PerGameCommonOptions
from dataclasses import dataclass

class Locations(OptionDict):
    "Autogenerated by True-Randomization"
    display_name = "locations"

class Items(OptionDict):
    "Autogenerated by True-Randomization"
    display_name = "items"

class Rules(OptionDict):
    "Autogenerated by True-Randomization"
    display_name = "rules"

@dataclass
class BloodstainedOptions(PerGameCommonOptions):
    death_link: DeathLink
    locations: Locations
    items: Items
    rules: Rules